FROM postgres:13
COPY init.sql /docker-entrypoint-initdb.d/
# COPY docker-entrypoint-initdb.d /docker-entrypoint-initdb.d
# USER root
# RUN chown postgres:postgres /docker-entrypoint-initdb.d/init.sql
# ENTRYPOINT ["docker-entrypoint.sh"]
# CMD ["postgres"]